### ISSUE TITLE
What is a PDU?

### ISSUE THREAD

**Issue by redfast00** [K3CAN/Misc#1]
I saw this on lobsters; could you maybe describe what a PDU is and what you can do with it?

> I was given a Baytech RPC-2 (managed, rack-mounted PDU)

**Comment by K3CAN** [comment]
A power distribution unit (PDU) is essentially a fancy name for a "power strip", although many are a lot more complex than that. 
More info on PDUs in general: https://en.wikipedia.org/wiki/Power_distribution_unit

The Baytech RPC-2 (Remote Power Control-2) is a rack-mounted, 6-outlet, 120v PDU. Each outlet can be toggles on or off via the RS 232 serial port.
